###############################################################################
#
#                        Travis CI configuration
#                        =======================
#
# This file configures the Continuous Integration server on travis-ci.org
#
###############################################################################

language: python

# This will route the build job to the new Travis build environment
sudo: false

# This is the script that will actually run the tests
script: ./test/simple_tests.py

# These are environment variables that are used to configure the
# tests.
#
#   - LILY_PLATFORM is the platform for which lilypond was
#                   compiled. Note that travis-ci is running 64 bit
#                   Linux virtual machines, hence `linux-64` is pretty
#                   much the only value that makes sense.
#
#   - LILY_VERSION is the version of lilypond with which we want to
#                  run the tests
env:
  - LILY_PLATFORM=linux-64 LILY_VERSION=2.18.2-1
  - LILY_PLATFORM=linux-64 LILY_VERSION=2.19.15-1
